### PR TITLE
added support for startExpression, endExpression (different from Jalangi's endExpression)

### PR DESCRIPTION
**Pull request by Haiyang-Sun**

### CODE REVIEW

**Comment by mwaldrich** [comment]
Thanks for the implementation!

After trying to use these callbacks in my own analyses, I have noticed a few things:

- Using an analysis that registers callbacks *in addition to* `startExpression` and `endExpression` produces some Truffle errors.
- The `endExpression` callback appears to be called *before* the expression has actually ended.

Both of these can be observed by running the following analysis, `analysis.js`:
```js
(function (sandbox) {
    function MyAnalysis() {
        this.write = function (iid, name, val, lhs, isGlobal, isScriptLocal) {
            console.log("write:", J$.iidToLocation(iid));
        };
        this.startExpression = function (iid, type) {
            console.log("expression starts:", J$.iidToLocation(iid), "type:", type);
        };

        this.endExpression = function (iid, type) {
            console.log("expression finishes:", J$.iidToLocation(iid), "type:", type);
        };
    }

    sandbox.analysis = new MyAnalysis();
})(J$);
```
on the following source code, `chainedAssignment.js`:
```js
var a = 2;
var b = 4;
var c = 5;
a = b = c;
```
Running the command `mx jalangi --analysis analysis.js chainedAssignment.js` yields:

```
expression starts: (chainedAssignment.js:1:2:6:2) type: AutonomousFunctionExpression
expression finishes: (chainedAssignment.js:1:2:6:2) type: AutonomousFunctionExpression
[e] a node has more than 1 profiling tags!!
[e] (chainedAssignment.js:1:67:1:72): com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen has tags: WriteVariableExpressionTag ExpressionTag 
expression starts: (chainedAssignment.js:1:71:1:72) type: JSConstantInteger
expression finishes: (chainedAssignment.js:1:71:1:72) type: JSConstantInteger
write: (chainedAssignment.js:1:67:1:72)
[e] a node has more than 1 profiling tags!!
[e] (chainedAssignment.js:2:5:2:10): com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen has tags: WriteVariableExpressionTag ExpressionTag 
expression starts: (chainedAssignment.js:2:9:2:10) type: JSConstantInteger
expression finishes: (chainedAssignment.js:2:9:2:10) type: JSConstantInteger
write: (chainedAssignment.js:2:5:2:10)
[e] a node has more than 1 profiling tags!!
[e] (chainedAssignment.js:3:5:3:10): com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen has tags: WriteVariableExpressionTag ExpressionTag 
expression starts: (chainedAssignment.js:3:9:3:10) type: JSConstantInteger
expression finishes: (chainedAssignment.js:3:9:3:10) type: JSConstantInteger
write: (chainedAssignment.js:3:5:3:10)
[e] a node has more than 1 profiling tags!!
[e] (chainedAssignment.js:4:1:4:10): com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen has tags: WriteVariableExpressionTag ExpressionTag 
[e] a node has more than 1 profiling tags!!
[e] (chainedAssignment.js:4:5:4:10): com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen has tags: WriteVariableExpressionTag ExpressionTag 
expression starts: (chainedAssignment.js:4:9:4:10) type: JSReadCurrentFrameSlot
expression finishes: (chainedAssignment.js:4:9:4:10) type: JSReadCurrentFrameSlot
write: (chainedAssignment.js:4:5:4:10)
write: (chainedAssignment.js:4:1:4:10)
```

In particular, the two `write` callbacks are occurring *after* the `endExpression` callback. If I understand [the Jalangi docs](https://github.com/Samsung/jalangi2/blob/4697b3f3d301d1352e2e2c45cb8d8ceb0b9e44cd/src/js/runtime/analysisCallbackTemplate.js#L589-L595) correctly, the correct order of callbacks should be:
```
...
expression starts: (chainedAssignment.js:4:9:4:10) type: JSReadCurrentFrameSlot
write: (chainedAssignment.js:4:5:4:10)
write: (chainedAssignment.js:4:1:4:10)
expression finishes: (chainedAssignment.js:4:9:4:10) type: JSReadCurrentFrameSlot
```

**Comment by Haiyang-Sun** [comment]
@mwaldrich Thanks for your feedback. The bug should be fixed now.

**Comment by mwaldrich** [comment]
Thanks for the quick fix! I pulled the new changes and the Truffle errors seem to be gone and the callbacks appear in the right order. However, I think the `endExpression` callback still does not match the Jalangi specification:

>This callback is called when an expression is evaluated and its value is discarded.
>For example, this callback is called when an expression statement completes its execution.

This is inconsistent with the callbacks I am now receiving:
```
expression starts: (chainedAssignment.js:4:1:4:10) type: JSWriteCurrentFrameSlot
expression starts: (chainedAssignment.js:4:5:4:10) type: JSWriteCurrentFrameSlot
expression starts: (chainedAssignment.js:4:9:4:10) type: JSReadCurrentFrameSlot
expression finishes: (chainedAssignment.js:4:9:4:10) type: JSReadCurrentFrameSlot
write: (chainedAssignment.js:4:5:4:10)
expression finishes: (chainedAssignment.js:4:5:4:10) type: JSWriteCurrentFrameSlot
write: (chainedAssignment.js:4:1:4:10)
expression finishes: (chainedAssignment.js:4:1:4:10) type: JSWriteCurrentFrameSlot
```
because the nested expressions' values *are not* being discarded. To fully match the Jalangi spec, I believe the callbacks should look like:
```
write: (chainedAssignment.js:4:5:4:10)
write: (chainedAssignment.js:4:1:4:10)
expression finishes: (chainedAssignment.js:4:1:4:10) type: JSWriteCurrentFrameSlot
```
I would not expect support of the symmetric `startExpression` callback (to signal the start of an expression whose value will be discarded) because Jalangi itself does not even support this.

It may be possible to determine which `endExpression` calls are signalling a discarded value *with the current callbacks* by maintaining a stack of expression types and paying close attention to the name of the type of expression to which the current value is returning. But this would introduce a dependency in my analysis on NodeProf's names for the types of expressions in the current JS spec. It would also be fairly slow to implement in JS.

Not sure if this is helpful, but in Jalangi, it seems the [`endExpression` callback is triggered by an instrumentation function `X1`](https://github.com/Samsung/jalangi2/blob/08f6f38abc2f5a09ffa48d173b7f0d92d6d8b110/src/js/runtime/analysis.js#L747-L753). Then, during the instrumentation, various program constructs that are known to discard values are *wrapped* with calls to `X1`. [Here's an example.](https://github.com/Samsung/jalangi2/blob/08f6f38abc2f5a09ffa48d173b7f0d92d6d8b110/src/js/instrument/esnstrument.js#L1510-L1516)

**Comment by Haiyang-Sun** [comment]
Hi, I don't get your point, can you copy paste the full trace you expect? 
The Jalangi description you put here itself is not clear, what is an "expression statement" (An "expression" is not a "statement"). 
There are two expressions and one statement in this line of code: ```a=b=c```. When ```b=c``` finishes, the expression is finished, we should have the first ```write``` and the first ```endExpression```. When the other expression ```a=...``` finishes, we have the second ```write``` and the second ```endExpression```.

**Comment by mwaldrich** [comment]
This is the full trace I expect:
```
expression finishes: (chainedAssignment.js:1:2:6:2) type: AutonomousFunctionExpression
write: (chainedAssignment.js:1:67:1:72)
expression finishes: (chainedAssignment.js:1:67:1:72) type: JSWriteCurrentFrameSlot
write: (chainedAssignment.js:2:5:2:10)
expression finishes: (chainedAssignment.js:2:5:2:10) type: JSWriteCurrentFrameSlot
write: (chainedAssignment.js:3:5:3:10)
expression finishes: (chainedAssignment.js:3:5:3:10) type: JSWriteCurrentFrameSlot
write: (chainedAssignment.js:4:5:4:10)
write: (chainedAssignment.js:4:1:4:10)
expression finishes: (chainedAssignment.js:4:1:4:10) type: JSWriteCurrentFrameSlot
```

I believe the Jalangi description means "expression statement" to be when an expression is used as a statement. In other words, `x = y` is an expression, and `x = y;` is an expression statement. In the last line of the example above:
- `b = c` is an expression. Since its value isn't discarded (it is used in the next expression), it wouldn't trigger `endExpression`;
- `a = b = c` is an expression, and since a semicolon immediately follows, its value is discarded and should trigger `endExpression`.

**Comment by Haiyang-Sun** [comment]
Is there any specific reason or case to have exactly the same ```endExpression``` as Jalangi (e.g., does it matter if an expression's value is discarded or not)? NodeProf aims to support general dynamic analysis, and most but not necessarily all Jalangi features. In this case here, I want to know if it's worthwhile to support ```endExpression``` in the way Jalangi does because it requires some non-trivial efforts. 
The current ```startExpression``` and ```endExpression``` in NodeProf are literally the start and end of the execution of an expression node in the AST.

**Comment by mwaldrich** [comment]
My team is looking to use Jalangi's `endExpression` behavior to track the flow of values throughout a program's execution, since it is easy to distinguish between when a value flows into its surrounding expression, and when it doesn't. `startExpression` and `endExpression` as they are currently implemented don't make this distinction.

However, `startExpression` and `endExpression` as they are currently implemented are useful and well-named. I personally think Jalangi's `endExpression` behavior should be supported under a different callback name, such as `discardValue`.

**Comment by Haiyang-Sun** [comment]
@mwaldrich We can either add a new callback or we add an extra argument in the current ```endExpression``` callback indicating if the expression's return value has been discarded. 
I will investigate how to implement it.

**Comment by mwaldrich** [comment]
I would greatly prefer a new callback, rather than tacking this onto the current `endExpression`. Our analysis is interested *only* in the new functionality, and requiring us to listen to every single sub-expression (with `endExpression`) would seriously slow down our analysis.

**Comment by mwaldrich** [comment]
Any update on the implementation of the new callback?

**Comment by mwaldrich** [comment]
Just pinging this to make sure it doesn't get lost in the other issues

**Comment by alexjordan** [comment]
@mwaldrich we settled on a proposal to implement the `discardValue` feature, but still have to test it.

**Comment by alexjordan** [comment]
@Haiyang-Sun I noticed that after updating the branch to the latest changes in Graal (and NodeProf), some of the expression callbacks in the tests are no longer issued. Any idea?

**Comment by Haiyang-Sun** [comment]
@alexjordan 
Yes, I confirm that we lost several expression events for the write access expressions after upgrading the graaljs version.

@eleinadani 
The bug can be reproduced with the following unit test:
```
    @Test
    public void varWrite() {
        evalWithTags("(()=>{var a = 42;})()", new Class<?>[]{StandardTags.ExpressionTag.class});

        enter(StandardTags.ExpressionTag.class, (e, r) -> {
            // function literal
            enter(StandardTags.ExpressionTag.class, (e2, r2) -> {

            }).exit();
            r.input(assertJSFunctionInput);

            // write event
            enter(StandardTags.ExpressionTag.class, (e2, r2) -> {
                // literal expression
                enter(StandardTags.ExpressionTag.class, (e3, r3) -> {
                }).exit(assertReturnValue(42));
                r2.input(42);
            }).exit();
        }).exit();
    }
```

The test passes with graal-js commit a04610a6a26a3822c5b2f0d28aebee95c5a43082 but failing with 369d03827e2d10e4bf5a14816b9e327af925741f

**Comment by alexjordan** [comment]
After discussing with @eleinadani the following became clear: Graal.js has previously tagged too many nodes as expressions. This included the variable declarations (`var foo = 42`) that we lost while working on this PR. Because the expression behavior is now as intended (and I updated the tests and results) I would move ahead and merge this PR. @mwaldrich if you require a callback for variable declarations, we can add support for statements as a new API.

NB: function declarations are still considered expressions atm., I'll raise that with @eleinadani separately.

**Comment by mwaldrich** [comment]
I think if I need to instrument variable declarations, I can use the `declare` callback. So this looks good to me.

**Pull request merged**
